name: Config Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq wget

    - name: Install latest sing-box
      run: |
        API="https://api.github.com/repos/SagerNet/sing-box/releases"

        URL=$(curl -s $API | jq -r '
        (map(select(.prerelease==true))[0] // map(select(.prerelease==false))[0])
        .assets[]
        | select(.name | test("linux.*amd64.*deb"))
        | .browser_download_url' | head -n1)

        echo "Download: $URL"

        wget -O sing-box.deb $URL
        sudo dpkg -i sing-box.deb
        sing-box version
        
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml
    - name: Download content
      run: |
        URL="https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Adguard.txt"
        OUTPUT_FILE="./rule/adservers.txt"

        curl -L $URL -o $OUTPUT_FILE

        if [ -f "$OUTPUT_FILE" ]; then
          echo "Download successful: $OUTPUT_FILE"
        else
          echo "Download failed."
          exit 1
        fi
    - name: Convert AdGuard DNS Filter to sing-box rule set
      run: |
        sing-box rule-set convert --type adguard --output ./rule/adservers.srs ./rule/adservers.txt
    - name: Run script
      run: python ./main.py
      working-directory: ./rule/
    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./rule/*.json
        git add ./rule/*.srs
        git add ./rule/*.txt

        # 检查是否有文件被修改
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update rules"
          git push
        fi
